CREATE TABLE IF NOT EXISTS users(
    id         INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    login      VARCHAR(250) NOT NULL,
    password   VARCHAR(250) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS users_login_idx ON users (login);
CREATE TABLE IF NOT EXISTS keys(
    id         INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_id     VARCHAR(3000) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS users_key_id_idx ON keys (user_id, key_id);
CREATE TABLE IF NOT EXISTS repositories(
    id          INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    path        VARCHAR(350) DEFAULT '',
    description VARCHAR(350) DEFAULT '',
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);
