CREATE TABLE IF NOT EXISTS users(
    id         INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    email      VARCHAR(250) DEFAULT '',
    password   VARCHAR(250) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS repositories(
    id         INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    path       VARCHAR(250) DEFAULT '',
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);